# Starter pipeline
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Running a Docker Build'
  name: NodeJS_Docker_Build
  inputs:
    containerRegistry: 'DockerHub Connection'
    repository: 'tpayne666/azurenodejs'
    command: 'buildAndPush'
    Dockerfile: 'nodejs/webapp/Dockerfile'
    buildContext: 'nodejs/webapp/'

