apiVersion: v1
kind: ConfigMap
metadata:
  name: drop-db
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
data:
  drop-database.sql: |-
    {{- $.Files.Get "files/db/sqlscripts/drop/drop-database.sql"  | nindent 6 -}}
