apiVersion: v1
kind: ConfigMap
metadata:
  name: create-db
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
data:
  create-database.sql: |-
    {{- $.Files.Get "files/db/sqlscripts/create/create-database.sql"  | nindent 6 -}}
