apiVersion: v1
kind: ConfigMap
metadata:
  name: install-data
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
data:
  install-data.sql: |-
    {{- $.Files.Get "files/db/sqlscripts/create/insert-app-schema.sql"  | nindent 6 -}}
