apiVersion: v1
kind: ConfigMap
metadata:
  name: drop-schema
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
data:
  drop-schema.sql: |-
    {{- $.Files.Get "files/db/sqlscripts/drop/drop-schema.sql"  | nindent 6 -}}
