apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbpgapp.fullname" . }}
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dbpgapp.selectorLabels" . | nindent 4 }}
