apiVersion: v1
kind: Secret
metadata:
  name: db-{{ include "dbpgapp.fullname" . }}
  labels:
    {{- include "dbpgapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.DbDeploy.secrets.password }}