name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: (cd csharp/WebRestAPI/WebRestAPI && docker build . --file Dockerfile --tag tpayne666/webrestapi:latest && docker rmi tpayne666/webrestapi:latest)
