name: GitHub CR Build and Push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      id:
        description: "run identifier"
        required: false
        default: "Job001"
        type: string

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  # github.repository as <account>/<repo>

concurrency:
  group: ${{ github.ref }}Docker
  cancel-in-progress: true

jobs:
  buildPush:
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/master')
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: ${{github.event.inputs.id}}
        run: echo Running job ${{github.event.inputs.id}}
      - name: Checkout repository
        uses: actions/checkout@v4

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@941183f0a080fa6be59a9e3d3f4108c19a528204

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
#      - name: Extract .Net Docker metadata
#        id: meta
#        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
#        with:
#          images: ${{ env.REGISTRY }}/${{ github.actor }}/webrestapi

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
#      - name: Build and Push .Net Docker image
#        id: build-and-push
#        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
#        with:
#          context: csharp/WebRestAPI/WebRestAPI/
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract CPPDemo Docker metadata
        id: meta1
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/cppdemo

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push CPPDemo Docker image
        id: build-and-push1
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: CPPExamples/Std11/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta1.outputs.tags }}
          labels: ${{ steps.meta1.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract CPP Docker metadata
        id: meta2
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/MessageUtils

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push CPP Docker image
        id: build-and-push2
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: CPPExamples/MessageUtils
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta2.outputs.tags }}
          labels: ${{ steps.meta2.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Docker metadata
        id: meta3
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejs

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Docker image
        id: build-and-push3
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/webapp/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta3.outputs.tags }}
          labels: ${{ steps.meta3.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS DB Docker metadata
        id: meta4
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejsdb

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS DB Docker image
        id: build-and-push4
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/dbops/app/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta4.outputs.tags }}
          labels: ${{ steps.meta4.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Azure Table Docker metadata
        id: meta5
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejsazuretable

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Azure Table Docker image
        id: build-and-push5
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/Azure/Table/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta5.outputs.tags }}
          labels: ${{ steps.meta5.outputs.labels }}


      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Azure File Docker metadata
        id: meta6
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejsazurefiles

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Azure Files Docker image
        id: build-and-push6
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/Azure/File/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta6.outputs.tags }}
          labels: ${{ steps.meta6.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Azure Graph Docker metadata
        id: meta7
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejsazurequery

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Azure Graph Docker image
        id: build-and-push7
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/Azure/Graph/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta7.outputs.tags }}
          labels: ${{ steps.meta7.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Python Chatbot Docker metadata
        id: meta8
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/chatbot

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push Python Chatbot Docker image
        id: build-and-push8
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: python/chatbot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta8.outputs.tags }}
          labels: ${{ steps.meta8.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Openai Chatbot Docker metadata
        id: meta9
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejschatbot

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Openai Chatbot Docker image
        id: build-and-push9
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/genai/openai/chatbot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta9.outputs.tags }}
          labels: ${{ steps.meta9.outputs.labels }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract NodeJS Gemini Chatbot Docker metadata
        id: meta10
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/nodejsgcpchatbot

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and Push NodeJS Gemini Chatbot Docker image
        id: build-and-push10
        uses: docker/build-push-action@88844b95d8cbbb41035fa9c94e5967a33b92db78
        with:
          context: nodejs/genai/gemini/chatbot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta10.outputs.tags }}
          labels: ${{ steps.meta10.outputs.labels }}