name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the .Netv5 Docker image
      run: (cd csharp/WebRestAPI/WebRestAPI && docker build . --file Dockerfile --tag tpayne666/webrestapi:latest && docker run --rm -t -d -p 5555:80 tpayne666/webrestapi:latest && sleep 15 && curl localhost:5555/api/repo/repostring && docker rmi -f docker rmi tpayne666/webrestapi:latest)
    - name: Build the .Netv6 Docker image
      run: (cd csharp/WebRestAPI/WebRestAPI && docker build . --file DockerfileV6 --tag tpayne666/webrestapi:csv6 && docker run --rm -t -d -p 5555:80 tpayne666/webrestapi:csv6 && sleep 15 && curl localhost:5555/api/repo/repostring && docker rmi -f tpayne666/webrestapi:csv6)
    - name: Build the CPP Docker image and test
      run: (cd CPPExamples && docker build . -f Dockerfile -t tpayne666/cppdemo:latest && docker run --rm -t tpayne666/cppdemo:latest && docker rmi tpayne666/cppdemo:latest)
    
    
    
