name: Pull the Image and Test
#
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package
on:
  registry_package:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - name: Run Test
      uses: addnab/docker-run-action@v3
      with:
        registry: ${{ github.event.repository.name }}
        image: ${{ github.event.repository.name }}
    - name: Run a command
      run: |
        ls
